name: Auto Commit LeetCode

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global user.name "Arty"
          git config --global user.email "artyomlord777@gmail.com"

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin main
          git checkout main
          git pull origin main
          git add .
          git diff --cached --quiet || git commit -m "🤖 Auto commit"
          git push origin main
