name: Auto Commit LeetCode Solutions

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Git
      run: |
        git config --global user.name "Arty"
        git config --global user.email "artyomlord777@gmail.com"

    - name: Override remote and force push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git fetch origin main --depth=1
        git checkout main
        git add .
        git diff --cached --quiet || git commit -m "🤖 Auto update LeetCode solutions"
        git push origin main --force

