name: Auto Commit LeetCode Solutions

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # disable default creds

    - name: Setup Git
      run: |
        git config --global user.name "Arty"
        git config --global user.email "artyomlord777@gmail.com"

    - name: Commit and Push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "🤖 Auto update LeetCode solutions" || echo "Nothing to commit"
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD --force
