name: Auto Commit LeetCode Solutions

on:
  schedule:
    - cron: '0 23 * * *'  # каждый день в 23:00 UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 🛑 отключаем встроенные креды

    - name: Set up Git
      run: |
        git config --global user.name "Arty"
        git config --global user.email "artyomlord777@gmail.com"

    - name: Commit & Push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git pull origin main --rebase || true
        git add .
        git diff-index --quiet HEAD || git commit -m "🤖 Auto update LeetCode solutions"
        git push origin HEAD:main --force
